export const TASK_ACTIONS = {
  HTTP_RESPONSE_NEW_TASKS: 'HTTP_RESPONSE_NEW_TASKS',
  HTTP_RESPONSE_NEW_TASKS_ERROR: 'HTTP_RESPONSE_NEW_TASKS_ERROR',
  HTTP_RESPONSE_ADD_TASKS_ERROR: 'HTTP_RESPONSE_ADD_TASKS_ERROR'
};
